services:
  fastapi:
    build:
      context: .
      dockerfile: ./docker/fastapi/Dockerfile
    env_file:
      - .env
    depends_on:
      - database
  database:
    image: postgres:15
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql
    ports:
      - '5432:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - '1000:8080'
volumes:
  data:
