name: MyPy

on: 
  workflow_dispatch:
  push:
    branches:
    - main
    - gh-actions-tests
  pull_request:
    branches:
    - main

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install mypy
        run: pip install mypy
      - name: Install dependencies
        run: pip install -r requirements/requirements.txt
      - name: Run mypy
        shell: bash
        run: mypy --ignore-missing-imports .
